//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringAccountTransfer.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecurringSetup()
        {
            this.RecurringSetupAttemptLogs = new HashSet<RecurringSetupAttemptLog>();
        }
    
        public long Id { get; set; }
        public string SourceAccountNumber { get; set; }
        public string SourceBankCode { get; set; }
        public string RecurringAlias { get; set; }
        public string DestinationBankCode { get; set; }
        public string DestinationAccountNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> RecurringFrequencyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Enable { get; set; }
        public string Purpose { get; set; }
        public string RecurringFrequency { get; set; }
        public long ProfileId { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Narration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringSetupAttemptLog> RecurringSetupAttemptLogs { get; set; }
    }
}
