//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecurringAccountTransfer.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringSetupAttemptLog
    {
        public long Id { get; set; }
        public long RecurringSetupId { get; set; }
        public bool IsSuccessful { get; set; }
        public System.DateTime DateAttempted { get; set; }
        public string DebitServiceResponse { get; set; }
    
        public virtual RecurringSetup RecurringSetup { get; set; }
    }
}
